### ISSUE TITLE
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.

### ISSUE THREAD

**Issue by wfq1971** [OutofAi/OutofFocus#5]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.

**Comment by OutofAi** [comment]
if you could provide more details please? there is currently a safety check that is enabled which is quite rudimentary , you can try a different prompt as the message suggested, hope that helps
